import re

with open("portfolio.html", "r") as f:
    content = f.read()

replacements = {
    # TITLE
    '<title>Portfólio — Moraes Engenharia | Obras Comerciais em SP e RJ</title>': '<title data-i18n="portfolio.title_tag">Portfólio — Moraes Engenharia | Obras Comerciais em SP e RJ</title>',

    # NAV & FOOTER (same as before)
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="index.html">Home</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="index.html" data-i18n="nav.home">Home</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="sobre.html">Sobre</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="sobre.html" data-i18n="nav.about">Sobre</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="sobre.html">Sobre</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="sobre.html" data-i18n="nav.about">Sobre</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="servicos.html">Serviços</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="servicos.html" data-i18n="nav.services">Serviços</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="servicos.html">Serviços</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="servicos.html" data-i18n="nav.services">Serviços</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="portfolio.html">Portfólio</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="portfolio.html" data-i18n="nav.portfolio">Portfólio</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="portfolio.html">Portfólio</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="portfolio.html" data-i18n="nav.portfolio">Portfólio</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="contato.html">Contato</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="contato.html" data-i18n="nav.contact">Contato</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="contato.html">Contato</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="contato.html" data-i18n="nav.contact">Contato</a>',
    '<span class="relative z-10 text-white">Fale Conosco</span>': '<span class="relative z-10 text-white" data-i18n="nav.cta">Fale Conosco</span>',

    '<a href="index.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Home</a>': '<a href="index.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.home">Home</a>',
    '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4">Sobre</a>': '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4" data-i18n="nav.about">Sobre</a>',
    '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Sobre</a>': '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.about">Sobre</a>',
    '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Serviços</a>': '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.services">Serviços</a>',
    '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4">Serviços</a>': '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4" data-i18n="nav.services">Serviços</a>',
    '<a href="portfolio.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Portfólio</a>': '<a href="portfolio.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.portfolio">Portfólio</a>',
    '<a href="contato.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Contato</a>': '<a href="contato.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.contact">Contato</a>',
    '<a href="contato.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4">Contato</a>': '<a href="contato.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4" data-i18n="nav.contact">Contato</a>',
    
    '<p class="font-body text-[11px] tracking-[0.3em] uppercase text-white/30 max-w-xs leading-loose">\n                Construções comerciais de alto padrão em São Paulo e Rio de Janeiro.\n            </p>': '<p class="font-body text-[11px] tracking-[0.3em] uppercase text-white/30 max-w-xs leading-loose" data-i18n="footer.tagline">\n                Construções comerciais de alto padrão em São Paulo e Rio de Janeiro.\n            </p>',
    '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2">Navegação</h4>': '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2" data-i18n="footer.nav_title">Navegação</h4>',
    '<a href="index.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Início</a>': '<a href="index.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.home">Início</a>',
    '<a href="sobre.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Sobre</a>': '<a href="sobre.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.about">Sobre</a>',
    '<a href="servicos.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Serviços</a>': '<a href="servicos.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.services">Serviços</a>',
    '<a href="portfolio.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Obras</a>': '<a href="portfolio.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.portfolio">Obras</a>',
    '<a href="contato.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Contato</a>': '<a href="contato.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.contact">Contato</a>',
    '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2">Escritório Central</h4>': '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2" data-i18n="footer.office_title">Escritório Central</h4>',
    '<p class="text-white/40 font-headline text-[10px] tracking-[0.4em] uppercase leading-loose">\n                Rua Boa Vista, 254 — Sala 1516<br>Centro Histórico, São Paulo\n            </p>': '<p class="text-white/40 font-headline text-[10px] tracking-[0.4em] uppercase leading-loose" data-i18n="footer.office_address">\n                Rua Boa Vista, 254 — Sala 1516<br>Centro Histórico, São Paulo\n            </p>',
    '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20">© 2026 Moraes Engenharia. Todos os direitos reservados.</p>': '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20" data-i18n="footer.copyright">© 2026 Moraes Engenharia. Todos os direitos reservados.</p>',
    '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20">CREA-SP 2884830 &nbsp;•&nbsp; CNPJ 47.457.237/0001-60</p>': '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20" data-i18n="footer.crea">CREA-SP 2884830 &nbsp;•&nbsp; CNPJ 47.457.237/0001-60</p>',

    # PAGE SPECIFIC
    '<div class="section-label mb-8">PROJ.ARCH // ARCHIVES</div>': '<div class="section-label mb-8" data-i18n="portfolio.label">PROJ.ARCH // ARCHIVES</div>',
    '<h2 class="font-headline text-5xl md:text-7xl font-black tracking-[-0.04em] uppercase text-white leading-[1.0]">\n                        Portfólio <br/> <span class="text-gold-premium italic font-light">Selecionado</span>.\n                    </h2>': '<h2 class="font-headline text-5xl md:text-7xl font-black tracking-[-0.04em] uppercase text-white leading-[1.0]" data-i18n="portfolio.title">\n                        Portfólio <br/> <span class="text-gold-premium italic font-light">Selecionado</span>.\n                    </h2>',

    # WORK 1
    '<span class="font-mono text-[9px] uppercase tracking-[0.4em] text-gold-premium block mb-3">Cubatão, SP</span>': '<span class="font-mono text-[9px] uppercase tracking-[0.4em] text-gold-premium block mb-3" data-i18n="portfolio.work1.location">Cubatão, SP</span>',
    '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]">Restauro Da Antiga Sede Associação de Socorros Mútuos</h3>': '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]" data-i18n="portfolio.work1.title">Restauro Da Antiga Sede Associação de Socorros Mútuos</h3>',
    '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl">\n                                Projeto de restauro e requalificação desenvolvido com foco na preservação histórica e valorização arquitetônica do imóvel. A intervenção contemplou a recuperação de elementos originais da edificação, adequações estruturais e adaptação dos ambientes para novos usos, mantendo a integridade do patrimônio cultural e reforçando a memória urbana da cidade.\n                            </p>': '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl" data-i18n="portfolio.work1.desc">\n                                Projeto de restauro e requalificação desenvolvido com foco na preservação histórica e valorização arquitetônica do imóvel. A intervenção contemplou a recuperação de elementos originais da edificação, adequações estruturais e adaptação dos ambientes para novos usos, mantendo a integridade do patrimônio cultural e reforçando a memória urbana da cidade.\n                            </p>',
    '<span class="text-white/40 text-[9px] uppercase tracking-[0.3em] block mb-1">Área Total</span>': '<span class="text-white/40 text-[9px] uppercase tracking-[0.3em] block mb-1" data-i18n="portfolio.area_label">Área Total</span>',
    '<span class="text-white/40 text-[9px] uppercase tracking-[0.3em] block mb-1">Duração</span>': '<span class="text-white/40 text-[9px] uppercase tracking-[0.3em] block mb-1" data-i18n="portfolio.duration_label">Duração</span>',
    '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold">11 Meses e 18 Dias</span>': '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold" data-i18n="portfolio.work1.duration">11 Meses e 18 Dias</span>',

    # WORK 2
    '<span class="font-mono text-[9px] uppercase tracking-[0.4em] text-gold-premium block mb-3">São Paulo, SP</span>': '<span class="font-mono text-[9px] uppercase tracking-[0.4em] text-gold-premium block mb-3" data-i18n="portfolio.work2.location">São Paulo, SP</span>',
    '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]">Modernização e Retrofit – Mercadão Municipal de São Paulo</h3>': '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]" data-i18n="portfolio.work2.title">Modernização e Retrofit – Mercadão Municipal de São Paulo</h3>',
    '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl">\n                                Projeto de retrofit e modernização executado em diferentes setores do Mercado Municipal de São Paulo, com foco na atualização da infraestrutura e melhoria das condições operacionais do complexo. A intervenção contemplou implantação de reservatório de água de reuso, impermeabilização, adequações hidro sanitárias, reforma e modernização do subsolo, execução de passarela técnica, modernização das instalações da SABESP e instalação de novos ladrilhos, garantindo maior eficiência, durabilidade e valorização do patrimônio público.\n                            </p>': '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl" data-i18n="portfolio.work2.desc">\n                                Projeto de retrofit e modernização executado em diferentes setores do Mercado Municipal de São Paulo, com foco na atualização da infraestrutura e melhoria das condições operacionais do complexo. A intervenção contemplou implantação de reservatório de água de reuso, impermeabilização, adequações hidro sanitárias, reforma e modernização do subsolo, execução de passarela técnica, modernização das instalações da SABESP e instalação de novos ladrilhos, garantindo maior eficiência, durabilidade e valorização do patrimônio público.\n                            </p>',
    '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold">12 Meses</span>': '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold" data-i18n="portfolio.work2.duration">12 Meses</span>',

    # WORK 3
    '<span class="font-mono text-[9px] uppercase tracking-[0.4em] text-gold-premium block mb-3">Mangaratiba, RJ</span>': '<span class="font-mono text-[9px] uppercase tracking-[0.4em] text-gold-premium block mb-3" data-i18n="portfolio.work3.location">Mangaratiba, RJ</span>',
    '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]">Condomínio Portobello Resort & Safari</h3>': '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]" data-i18n="portfolio.work3.title">Condomínio Portobello Resort & Safari</h3>',
    '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl">\n                                Projeto residencial de alto padrão executado com estrutura metálica, marcado por grandes vãos livres, balanços arquitetônicos expressivos e soluções estruturais de alta precisão. A obra reúne engenharia aplicada, desempenho estrutural e arquitetura contemporânea em um projeto que desafia limites técnicos e exige controle rigoroso em cada etapa executiva. Com execução estratégica e atenção absoluta aos detalhes, o projeto integra imponência estética, eficiência construtiva e performance estrutural em uma residência única dentro do Portobello Resort & Safari.\n                            </p>': '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl" data-i18n="portfolio.work3.desc">\n                                Projeto residencial de alto padrão executado com estrutura metálica, marcado por grandes vãos livres, balanços arquitetônicos expressivos e soluções estruturais de alta precisão. A obra reúne engenharia aplicada, desempenho estrutural e arquitetura contemporânea em um projeto que desafia limites técnicos e exige controle rigoroso em cada etapa executiva. Com execução estratégica e atenção absoluta aos detalhes, o projeto integra imponência estética, eficiência construtiva e performance estrutural em uma residência única dentro do Portobello Resort & Safari.\n                            </p>',
    '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold">5 Meses</span>': '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold" data-i18n="portfolio.work3.duration">5 Meses</span>',

    # WORK 4
    '<span class="font-mono text-[9px] uppercase tracking-[0.4em] text-gold-premium block mb-3">Zona Sul, SP</span>': '<span class="font-mono text-[9px] uppercase tracking-[0.4em] text-gold-premium block mb-3" data-i18n="portfolio.work4.location">Zona Sul, SP</span>',
    '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]">Loja Comercial</h3>': '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]" data-i18n="portfolio.work4.title">Loja Comercial</h3>',
    '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl">\n                                Projeto comercial executado em estrutura metálica com mezanino, desenvolvido com foco em agilidade construtiva, precisão técnica e alto desempenho executivo. A obra exigiu planejamento estratégico, controle operacional e rápida tomada de decisão em campo para garantir produtividade e cumprimento rigoroso do cronograma. Cada etapa foi conduzida com organização, eficiência e qualidade de execução, resultando em uma entrega dentro do prazo e alinhada ao padrão exigido pelo projeto.\n                            </p>': '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl" data-i18n="portfolio.work4.desc">\n                                Projeto comercial executado em estrutura metálica com mezanino, desenvolvido com foco em agilidade construtiva, precisão técnica e alto desempenho executivo. A obra exigiu planejamento estratégico, controle operacional e rápida tomada de decisão em campo para garantir produtividade e cumprimento rigoroso do cronograma. Cada etapa foi conduzida com organização, eficiência e qualidade de execução, resultando em uma entrega dentro do prazo e alinhada ao padrão exigido pelo projeto.\n                            </p>',
    '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold">6 Meses</span>': '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold" data-i18n="portfolio.work4.duration">6 Meses</span>',

    # WORK 5
    '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]">Reforma, Adequação e Modernização de Galpão Logístico</h3>': '<h3 class="text-white text-3xl lg:text-4xl xl:text-5xl font-black uppercase tracking-tight mb-6 leading-[1.1]" data-i18n="portfolio.work5.title">Reforma, Adequação e Modernização de Galpão Logístico</h3>',
    '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl">\n                                Projeto de reforma e modernização de galpão logístico desenvolvido para ampliação da eficiência operacional e valorização estrutural do empreendimento. A intervenção contemplou substituição completa do telhado, restauro e tratamento do madeiramento, troca das telhas, nivelamento do piso industrial, modernização dos banheiros, renovação integral das instalações elétricas e iluminação, recuperação de alvenaria e pintura geral. O projeto também incluiu reforço estrutural metálico e redução de 11 pilares de concreto, ampliando significativamente a área útil de circulação e otimizando a funcionalidade do espaço.\n                            </p>': '<p class="text-on-surface-variant/80 text-sm md:text-base leading-relaxed font-light mb-8 max-w-2xl" data-i18n="portfolio.work5.desc">\n                                Projeto de reforma e modernização de galpão logístico desenvolvido para ampliação da eficiência operacional e valorização estrutural do empreendimento. A intervenção contemplou substituição completa do telhado, restauro e tratamento do madeiramento, troca das telhas, nivelamento do piso industrial, modernização dos banheiros, renovação integral das instalações elétricas e iluminação, recuperação de alvenaria e pintura geral. O projeto também incluiu reforço estrutural metálico e redução de 11 pilares de concreto, ampliando significativamente a área útil de circulação e otimizando a funcionalidade do espaço.\n                            </p>',
    '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold">4 Meses</span>': '<span class="text-white font-mono text-[11px] uppercase tracking-[0.2em] font-bold" data-i18n="portfolio.work5.duration">4 Meses</span>',
    
    # BEFORE/AFTER LABELS
    '<span class="bg-black/60 text-white font-mono text-[10px] uppercase tracking-[0.2em] px-4 py-2 backdrop-blur-md border border-white/10 rounded-sm">ANTES</span>': '<span class="bg-black/60 text-white font-mono text-[10px] uppercase tracking-[0.2em] px-4 py-2 backdrop-blur-md border border-white/10 rounded-sm" data-i18n="portfolio.before">ANTES</span>',
    '<span class="bg-gold-premium/90 text-white font-mono text-[10px] uppercase tracking-[0.2em] px-4 py-2 backdrop-blur-md border border-white/10 rounded-sm">DEPOIS</span>': '<span class="bg-gold-premium/90 text-white font-mono text-[10px] uppercase tracking-[0.2em] px-4 py-2 backdrop-blur-md border border-white/10 rounded-sm" data-i18n="portfolio.after">DEPOIS</span>',
}

for old, new in replacements.items():
    content = content.replace(old, new)

# Toggle button
if 'class="lang-toggle' not in content:
    toggle_html = '<button class="lang-toggle font-headline uppercase tracking-[0.2em] text-[10px] font-bold text-white/70 hover:text-gold-premium transition-all interactive border border-white/15 hover:border-gold-premium/50 px-3 py-2 mr-4 lg:ml-8" type="button">中文</button>'
    content = content.replace('<button class="lg:hidden', f'{toggle_html}\n        <button class="lg:hidden')

# Script
if '<script src="translations.js"></script>' not in content:
    content = content.replace('</body>', '<script src="translations.js"></script>\n</body>')

with open("portfolio.html", "w") as f:
    f.write(content)

print("portfolio.html updated")
