import re

with open("sobre.html", "r") as f:
    content = f.read()

replacements = {
    # TITLE
    '<title>Sobre Nós — Moraes Engenharia | Construtora de Alto Padrão em SP e RJ</title>': '<title data-i18n="about.title_tag">Sobre Nós — Moraes Engenharia | Construtora de Alto Padrão em SP e RJ</title>',

    # NAV & FOOTER
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="index.html">Home</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="index.html" data-i18n="nav.home">Home</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="sobre.html">Sobre</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="sobre.html" data-i18n="nav.about">Sobre</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="servicos.html">Serviços</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="servicos.html" data-i18n="nav.services">Serviços</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="portfolio.html">Portfólio</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="portfolio.html" data-i18n="nav.portfolio">Portfólio</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="contato.html">Contato</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="contato.html" data-i18n="nav.contact">Contato</a>',
    '<span class="relative z-10 text-white">Fale Conosco</span>': '<span class="relative z-10 text-white" data-i18n="nav.cta">Fale Conosco</span>',

    '<a href="index.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Home</a>': '<a href="index.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.home">Home</a>',
    '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4">Sobre</a>': '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4" data-i18n="nav.about">Sobre</a>',
    '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Serviços</a>': '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.services">Serviços</a>',
    '<a href="portfolio.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Portfólio</a>': '<a href="portfolio.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.portfolio">Portfólio</a>',
    '<a href="contato.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Contato</a>': '<a href="contato.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.contact">Contato</a>',
    
    '<p class="font-body text-[11px] tracking-[0.3em] uppercase text-white/30 max-w-xs leading-loose">\n                Construções comerciais de alto padrão em São Paulo e Rio de Janeiro.\n            </p>': '<p class="font-body text-[11px] tracking-[0.3em] uppercase text-white/30 max-w-xs leading-loose" data-i18n="footer.tagline">\n                Construções comerciais de alto padrão em São Paulo e Rio de Janeiro.\n            </p>',
    '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2">Navegação</h4>': '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2" data-i18n="footer.nav_title">Navegação</h4>',
    '<a href="index.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Início</a>': '<a href="index.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.home">Início</a>',
    '<a href="sobre.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Sobre</a>': '<a href="sobre.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.about">Sobre</a>',
    '<a href="servicos.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Serviços</a>': '<a href="servicos.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.services">Serviços</a>',
    '<a href="portfolio.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Obras</a>': '<a href="portfolio.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.portfolio">Obras</a>',
    '<a href="contato.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Contato</a>': '<a href="contato.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.contact">Contato</a>',
    '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2">Escritório Central</h4>': '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2" data-i18n="footer.office_title">Escritório Central</h4>',
    '<p class="text-white/40 font-headline text-[10px] tracking-[0.4em] uppercase leading-loose">\n                Rua Boa Vista, 254 — Sala 1516<br>Centro Histórico, São Paulo\n            </p>': '<p class="text-white/40 font-headline text-[10px] tracking-[0.4em] uppercase leading-loose" data-i18n="footer.office_address">\n                Rua Boa Vista, 254 — Sala 1516<br>Centro Histórico, São Paulo\n            </p>',
    '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20">© 2026 Moraes Engenharia. Todos os direitos reservados.</p>': '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20" data-i18n="footer.copyright">© 2026 Moraes Engenharia. Todos os direitos reservados.</p>',
    '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20">CREA-SP 2884830 &nbsp;•&nbsp; CNPJ 47.457.237/0001-60</p>': '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20" data-i18n="footer.crea">CREA-SP 2884830 &nbsp;•&nbsp; CNPJ 47.457.237/0001-60</p>',

    # PAGE SPECIFIC - SOBRE
    '<div class="section-label mb-8">02 // QUEM SOMOS</div>': '<div class="section-label mb-8" data-i18n="about.label">02 // QUEM SOMOS</div>',
    '<h2 class="font-headline text-4xl sm:text-5xl md:text-7xl font-black tracking-[-0.04em] uppercase text-white mb-12 leading-[1.0]">\n                        Mais do que Estruturas. <br/> <span class="text-gold-premium italic font-light">Relações</span> de Valor.\n                    </h2>': '<h2 class="font-headline text-4xl sm:text-5xl md:text-7xl font-black tracking-[-0.04em] uppercase text-white mb-12 leading-[1.0]" data-i18n="about.title">\n                        Mais do que Estruturas. <br/> <span class="text-gold-premium italic font-light">Relações</span> de Valor.\n                    </h2>',
    '<p class="text-on-surface-variant text-base md:text-xl leading-relaxed font-light">\n                            A Moraes Engenharia nasceu em 2018, quando Lucas Moraes realizou sua primeira obra comercial para um cliente do mercado de importação no centro de São Paulo. O que começou como um projeto pontual se transformou em uma relação de confiança — e essa confiança se tornou o alicerce de tudo que viria depois.\n                        </p>': '<p class="text-on-surface-variant text-base md:text-xl leading-relaxed font-light" data-i18n="about.p1">\n                            A Moraes Engenharia nasceu em 2018, quando Lucas Moraes realizou sua primeira obra comercial para um cliente do mercado de importação no centro de São Paulo. O que começou como um projeto pontual se transformou em uma relação de confiança — e essa confiança se tornou o alicerce de tudo que viria depois.\n                        </p>',
    '<p class="text-on-surface-variant text-base md:text-xl leading-relaxed font-light mt-4">\n                            De uma reforma comercial na 25 de Março a construções verticais de grande porte, a trajetória da Moraes foi construída projeto a projeto, com uma premissa inegociável: cada obra precisa ser melhor que a anterior.\n                        </p>': '<p class="text-on-surface-variant text-base md:text-xl leading-relaxed font-light mt-4" data-i18n="about.p2">\n                            De uma reforma comercial na 25 de Março a construções verticais de grande porte, a trajetória da Moraes foi construída projeto a projeto, com uma premissa inegociável: cada obra precisa ser melhor que a anterior.\n                        </p>',
    '<span class="text-white/40 font-mono uppercase text-[11px] md:text-[11px] tracking-[0.4em]">Anos de Mercado Comercial</span>': '<span class="text-white/40 font-mono uppercase text-[11px] md:text-[11px] tracking-[0.4em]" data-i18n="about.stats.years">Anos de Mercado Comercial</span>',
    '<span class="text-white/40 font-mono uppercase text-[11px] md:text-[11px] tracking-[0.4em]">Obras Entregues (SP e RJ)</span>': '<span class="text-white/40 font-mono uppercase text-[11px] md:text-[11px] tracking-[0.4em]" data-i18n="about.stats.works">Obras Entregues (SP e RJ)</span>',
    '<span class="text-white/40 font-mono uppercase text-[11px] md:text-[11px] tracking-[0.4em]">M² Construídos (Média)</span>': '<span class="text-white/40 font-mono uppercase text-[11px] md:text-[11px] tracking-[0.4em]" data-i18n="about.stats.area">M² Construídos (Média)</span>',
    '<p class="font-mono text-[11px] tracking-[0.3em] uppercase text-gold-premium border-l border-gold-premium/30 pl-4">Lucas Moraes // Direção Geral</p>': '<p class="font-mono text-[11px] tracking-[0.3em] uppercase text-gold-premium border-l border-gold-premium/30 pl-4" data-i18n="about.team.lucas">Lucas Moraes // Direção Geral</p>',
    '<p class="font-mono text-[11px] tracking-[0.3em] uppercase text-gold-premium border-l border-gold-premium/30 pl-4">Corpo Técnico SP & RJ</p>': '<p class="font-mono text-[11px] tracking-[0.3em] uppercase text-gold-premium border-l border-gold-premium/30 pl-4" data-i18n="about.team.staff">Corpo Técnico SP & RJ</p>',
    '<h4 class="text-white font-headline text-lg uppercase tracking-widest font-bold mb-4">Prazo</h4>': '<h4 class="text-white font-headline text-lg uppercase tracking-widest font-bold mb-4" data-i18n="about.pillar1.title">Prazo</h4>',
    '<p class="text-on-surface-variant/70 text-sm font-light leading-relaxed">Prazo é contrato moral. Atraso não é opção, é exceção com plano de ação.</p>': '<p class="text-on-surface-variant/70 text-sm font-light leading-relaxed" data-i18n="about.pillar1.desc">Prazo é contrato moral. Atraso não é opção, é exceção com plano de ação.</p>',
    '<h4 class="text-white font-headline text-lg uppercase tracking-widest font-bold mb-4">Execução</h4>': '<h4 class="text-white font-headline text-lg uppercase tracking-widest font-bold mb-4" data-i18n="about.pillar2.title">Execução</h4>',
    '<p class="text-on-surface-variant/70 text-sm font-light leading-relaxed">Fazer certo na primeira vez. Padrão alto é nossa obrigação.</p>': '<p class="text-on-surface-variant/70 text-sm font-light leading-relaxed" data-i18n="about.pillar2.desc">Fazer certo na primeira vez. Padrão alto é nossa obrigação.</p>',
    '<h4 class="text-white font-headline text-lg uppercase tracking-widest font-bold mb-4">Cliente</h4>': '<h4 class="text-white font-headline text-lg uppercase tracking-widest font-bold mb-4" data-i18n="about.pillar3.title">Cliente</h4>',
    '<p class="text-on-surface-variant/70 text-sm font-light leading-relaxed">Comunicação clara e postura profissional. Entrega além da expectativa.</p>': '<p class="text-on-surface-variant/70 text-sm font-light leading-relaxed" data-i18n="about.pillar3.desc">Comunicação clara e postura profissional. Entrega além da expectativa.</p>'
}

for old, new in replacements.items():
    content = content.replace(old, new)

# Toggle button
if 'class="lang-toggle' not in content:
    toggle_html = '<button class="lang-toggle font-headline uppercase tracking-[0.2em] text-[10px] font-bold text-white/70 hover:text-gold-premium transition-all interactive border border-white/15 hover:border-gold-premium/50 px-3 py-2 mr-4 lg:ml-8" type="button">中文</button>'
    content = content.replace('<button class="lg:hidden', f'{toggle_html}\n        <button class="lg:hidden')

# Script
if '<script src="translations.js"></script>' not in content:
    content = content.replace('</body>', '<script src="translations.js"></script>\n</body>')

with open("sobre.html", "w") as f:
    f.write(content)

print("sobre.html updated")
