import re

with open("servicos.html", "r") as f:
    content = f.read()

replacements = {
    # TITLE
    '<title>Serviços — Moraes Engenharia | Construções Verticais, Galpões e Reformas em SP e RJ</title>': '<title data-i18n="services.title_tag">Serviços — Moraes Engenharia | Construções Verticais, Galpões e Reformas em SP e RJ</title>',

    # NAV & FOOTER (same as before)
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="index.html">Home</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="index.html" data-i18n="nav.home">Home</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="sobre.html">Sobre</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="sobre.html" data-i18n="nav.about">Sobre</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="sobre.html">Sobre</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="sobre.html" data-i18n="nav.about">Sobre</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="servicos.html">Serviços</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="servicos.html" data-i18n="nav.services">Serviços</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="servicos.html">Serviços</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="servicos.html" data-i18n="nav.services">Serviços</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="portfolio.html">Portfólio</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="portfolio.html" data-i18n="nav.portfolio">Portfólio</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="portfolio.html">Portfólio</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-gold-premium transition-all interactive" href="portfolio.html" data-i18n="nav.portfolio">Portfólio</a>',
    '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="contato.html">Contato</a>': '<a class="font-headline uppercase tracking-[0.3em] text-[11px] font-bold text-white/50 hover:text-white transition-all interactive" href="contato.html" data-i18n="nav.contact">Contato</a>',
    '<span class="relative z-10 text-white">Fale Conosco</span>': '<span class="relative z-10 text-white" data-i18n="nav.cta">Fale Conosco</span>',

    '<a href="index.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Home</a>': '<a href="index.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.home">Home</a>',
    '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4">Sobre</a>': '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4" data-i18n="nav.about">Sobre</a>',
    '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Sobre</a>': '<a href="sobre.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.about">Sobre</a>',
    '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Serviços</a>': '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.services">Serviços</a>',
    '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4">Serviços</a>': '<a href="servicos.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-gold-premium font-bold interactive mt-4" data-i18n="nav.services">Serviços</a>',
    '<a href="portfolio.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Portfólio</a>': '<a href="portfolio.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.portfolio">Portfólio</a>',
    '<a href="contato.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4">Contato</a>': '<a href="contato.html" class="font-headline text-2xl uppercase tracking-[0.3em] text-white hover:text-gold-premium font-bold interactive mt-4" data-i18n="nav.contact">Contato</a>',
    
    '<p class="font-body text-[11px] tracking-[0.3em] uppercase text-white/30 max-w-xs leading-loose">\n                Construções comerciais de alto padrão em São Paulo e Rio de Janeiro.\n            </p>': '<p class="font-body text-[11px] tracking-[0.3em] uppercase text-white/30 max-w-xs leading-loose" data-i18n="footer.tagline">\n                Construções comerciais de alto padrão em São Paulo e Rio de Janeiro.\n            </p>',
    '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2">Navegação</h4>': '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2" data-i18n="footer.nav_title">Navegação</h4>',
    '<a href="index.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Início</a>': '<a href="index.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.home">Início</a>',
    '<a href="sobre.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Sobre</a>': '<a href="sobre.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.about">Sobre</a>',
    '<a href="servicos.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Serviços</a>': '<a href="servicos.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.services">Serviços</a>',
    '<a href="portfolio.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Obras</a>': '<a href="portfolio.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.portfolio">Obras</a>',
    '<a href="contato.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive">Contato</a>': '<a href="contato.html" class="text-white/40 hover:text-white font-headline text-[10px] tracking-[0.4em] uppercase transition-colors duration-300 interactive" data-i18n="footer.nav.contact">Contato</a>',
    '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2">Escritório Central</h4>': '<h4 class="text-gold-premium font-headline font-bold text-[11px] uppercase tracking-[0.5em] mb-2" data-i18n="footer.office_title">Escritório Central</h4>',
    '<p class="text-white/40 font-headline text-[10px] tracking-[0.4em] uppercase leading-loose">\n                Rua Boa Vista, 254 — Sala 1516<br>Centro Histórico, São Paulo\n            </p>': '<p class="text-white/40 font-headline text-[10px] tracking-[0.4em] uppercase leading-loose" data-i18n="footer.office_address">\n                Rua Boa Vista, 254 — Sala 1516<br>Centro Histórico, São Paulo\n            </p>',
    '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20">© 2026 Moraes Engenharia. Todos os direitos reservados.</p>': '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20" data-i18n="footer.copyright">© 2026 Moraes Engenharia. Todos os direitos reservados.</p>',
    '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20">CREA-SP 2884830 &nbsp;•&nbsp; CNPJ 47.457.237/0001-60</p>': '<p class="font-mono text-[9px] sm:text-[10px] tracking-[0.2em] uppercase text-white/20" data-i18n="footer.crea">CREA-SP 2884830 &nbsp;•&nbsp; CNPJ 47.457.237/0001-60</p>',

    # PAGE SPECIFIC - SERVICOS
    '<div class="section-label mb-8">03 // OPERAÇÕES</div>': '<div class="section-label mb-8" data-i18n="services.label">03 // OPERAÇÕES</div>',
    '<h2 class="font-headline text-4xl sm:text-5xl md:text-7xl font-black tracking-[-0.04em] uppercase text-white leading-[1.0]">\n                        Nossas <br/><span class="text-gold-premium italic font-light">Expertises</span>.\n                    </h2>': '<h2 class="font-headline text-4xl sm:text-5xl md:text-7xl font-black tracking-[-0.04em] uppercase text-white leading-[1.0]" data-i18n="services.title">\n                        Nossas <br/><span class="text-gold-premium italic font-light">Expertises</span>.\n                    </h2>',
    '<p class="text-on-surface-variant/60 text-xs sm:text-sm font-mono uppercase tracking-[0.3em] max-w-xs mb-4 leading-relaxed">\n                    Execução técnica absoluta. Sem concessões, independente da escala do projeto.\n                </p>': '<p class="text-on-surface-variant/60 text-xs sm:text-sm font-mono uppercase tracking-[0.3em] max-w-xs mb-4 leading-relaxed" data-i18n="services.subtitle">\n                    Execução técnica absoluta. Sem concessões, independente da escala do projeto.\n                </p>',
    '<h3 class="font-headline font-extrabold text-xl md:text-2xl text-white uppercase tracking-tight mb-4 group-hover:text-gold-premium/90 transition-colors duration-300">Construções Verticais</h3>': '<h3 class="font-headline font-extrabold text-xl md:text-2xl text-white uppercase tracking-tight mb-4 group-hover:text-gold-premium/90 transition-colors duration-300" data-i18n="services.1.title">Construções Verticais</h3>',
    '<p class="text-on-surface-variant/60 text-sm leading-relaxed font-light max-w-2xl">Edifícios comerciais projetados para máxima eficiência de uso. Estruturas pensadas para operação, locação por andar ou uso próprio, com padrão construtivo que valoriza o investimento no longo prazo.</p>': '<p class="text-on-surface-variant/60 text-sm leading-relaxed font-light max-w-2xl" data-i18n="services.1.desc">Edifícios comerciais projetados para máxima eficiência de uso. Estruturas pensadas para operação, locação por andar ou uso próprio, com padrão construtivo que valoriza o investimento no longo prazo.</p>',
    '<h3 class="font-headline font-extrabold text-xl md:text-2xl text-white uppercase tracking-tight mb-4 group-hover:text-gold-premium/90 transition-colors duration-300">Galpões Industriais e Comerciais</h3>': '<h3 class="font-headline font-extrabold text-xl md:text-2xl text-white uppercase tracking-tight mb-4 group-hover:text-gold-premium/90 transition-colors duration-300" data-i18n="services.2.title">Galpões Industriais e Comerciais</h3>',
    '<p class="text-on-surface-variant/60 text-sm leading-relaxed font-light max-w-2xl">Estruturas de grande porte para operação logística, estoque ou comércio. Projetos dimensionados conforme a necessidade do negócio, com foco em funcionalidade, resistência e prazo de entrega.</p>': '<p class="text-on-surface-variant/60 text-sm leading-relaxed font-light max-w-2xl" data-i18n="services.2.desc">Estruturas de grande porte para operação logística, estoque ou comércio. Projetos dimensionados conforme a necessidade do negócio, com foco em funcionalidade, resistência e prazo de entrega.</p>',
    '<h3 class="font-headline font-extrabold text-xl md:text-2xl text-white uppercase tracking-tight mb-4 group-hover:text-gold-premium/90 transition-colors duration-300">Reformas Estruturais</h3>': '<h3 class="font-headline font-extrabold text-xl md:text-2xl text-white uppercase tracking-tight mb-4 group-hover:text-gold-premium/90 transition-colors duration-300" data-i18n="services.3.title">Reformas Estruturais</h3>',
    '<p class="text-on-surface-variant/60 text-sm leading-relaxed font-light max-w-2xl">Transformação de imóveis existentes para nova finalidade comercial. Demolição parcial ou total e reconstrução com projeto atualizado, mantendo viabilidade técnica e conformidade legal.</p>': '<p class="text-on-surface-variant/60 text-sm leading-relaxed font-light max-w-2xl" data-i18n="services.3.desc">Transformação de imóveis existentes para nova finalidade comercial. Demolição parcial ou total e reconstrução com projeto atualizado, mantendo viabilidade técnica e conformidade legal.</p>',
    '<h3 class="font-headline font-extrabold text-xl md:text-2xl text-white uppercase tracking-tight mb-4 group-hover:text-gold-premium/90 transition-colors duration-300">Gestão de Obras</h3>': '<h3 class="font-headline font-extrabold text-xl md:text-2xl text-white uppercase tracking-tight mb-4 group-hover:text-gold-premium/90 transition-colors duration-300" data-i18n="services.4.title">Gestão de Obras</h3>',
    '<p class="text-on-surface-variant/60 text-sm leading-relaxed font-light max-w-2xl">Controle completo de cronograma, orçamento e qualidade. Relatórios periódicos, comunicação transparente e resolução ágil de imprevistos. O cliente acompanha cada etapa com segurança.</p>': '<p class="text-on-surface-variant/60 text-sm leading-relaxed font-light max-w-2xl" data-i18n="services.4.desc">Controle completo de cronograma, orçamento e qualidade. Relatórios periódicos, comunicação transparente e resolução ágil de imprevistos. O cliente acompanha cada etapa com segurança.</p>'
}

for old, new in replacements.items():
    content = content.replace(old, new)

# Toggle button
if 'class="lang-toggle' not in content:
    toggle_html = '<button class="lang-toggle font-headline uppercase tracking-[0.2em] text-[10px] font-bold text-white/70 hover:text-gold-premium transition-all interactive border border-white/15 hover:border-gold-premium/50 px-3 py-2 mr-4 lg:ml-8" type="button">中文</button>'
    content = content.replace('<button class="lg:hidden', f'{toggle_html}\n        <button class="lg:hidden')

# Script
if '<script src="translations.js"></script>' not in content:
    content = content.replace('</body>', '<script src="translations.js"></script>\n</body>')

with open("servicos.html", "w") as f:
    f.write(content)

print("servicos.html updated")
